sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
language: python
python: "3.7"
script:
  - pip install -e .
  - restrained_ESP_fit
addons:
    apt:
        packages: gfortran
    homebrew:
        packages: gfortran
