sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.7"
    - os: osx
      osx_image: xcode11.5
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION="3.7"
script:
  - pip3 install -e .
  - restrained_ESP_fit
addons:
    apt:
        packages: gfortran
    homebrew:
        packages: gfortran
